"use client";

import { useEffect, useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Code2, Copy, Flag, Heart, MessageCircle, Lightbulb, Menu, Monitor, MousePointer2, Pause, Play, Puzzle, RotateCcw, Sparkles, Terminal, Users, X } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import CodingWorld from "./coding-world";

function Instagram({ size = 20 }: { size?: number }) {
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".75" fill="currentColor" stroke="none"/></svg>;
}
const whatsapp = (course = "your coding classes") => `https://wa.me/96181954659?text=${encodeURIComponent(`Hi KiddyCody! I’m interested in ${course}. Could you tell me about the next group, schedule, and price?`)}`;
const instagram = "https://www.instagram.com/kiddycody.academy/";
const courses = [
  { id: "scratch", number: "01", title: "Scratch", subtitle: "Little blocks. Limitless imagination.", age: "7–14", className: "scratch", icon: Puzzle, description: "Turn playful ideas into games, stories, and animations. Learn how code works, one colorful block at a time.", skills: ["Creative thinking", "Loops & logic", "Games & stories"], detail: "A playful introduction to programming with visual blocks. Students work through ideas step by step and bring their own games, stories, and animations to life.", outcomes: ["Use events, loops, and conditions", "Make characters respond and interact", "Build and explain a project of their own"], examples: "Games, interactive stories, and animated characters" },
  { id: "python", number: "02", title: "Python", subtitle: "Big ideas meet real code.", age: "14–20", className: "python", icon: Terminal, description: "Go from your first line of code to programs of your own. Build confidence through hands-on practice.", skills: ["Problem solving", "Real programs", "Creative projects"], detail: "Learn to turn a problem into a working program. Python offers an approachable way to practice programming and start creating useful projects.", outcomes: ["Work with variables, conditions, and loops", "Break problems into reusable functions", "Build and debug small programs"], examples: "Quizzes, calculators, and useful little tools" },
  { id: "c", number: "03", title: "C Programming", subtitle: "Understand the how. Build the why.", age: "14–20", className: "clang", icon: Code2, description: "Build a solid programming foundation. Explore how programs work and learn to think like a developer.", skills: ["Strong foundations", "Structured thinking", "Core concepts"], detail: "Explore the building blocks of programming through C. Practice clear, structured thinking and learn how to write, run, and improve your programs.", outcomes: ["Understand types, variables, and control flow", "Organize code with functions and arrays", "Practice debugging and logical problem solving"], examples: "Number games, logic challenges, and console programs" },
];
const snippets = {
  scratch: { code: ["when green flag clicked", "say [Hello, creator!]", "repeat (3)", "    say [I can make something!]"], output: ["Hello, creator!", "I can make something!", "I can make something!", "I can make something!"] },
  python: { code: ['name = "Creator"', 'print(f"Hello, {name}!")', '', 'for idea in range(1, 4):', '    print(f"Idea {idea}: let’s build it!")'], output: ["Hello, Creator!", "Idea 1: let’s build it!", "Idea 2: let’s build it!", "Idea 3: let’s build it!"] },
  c: { code: ['#include <stdio.h>', '', 'int main(void) {', '    printf("Hello, creator!\\n");', '    return 0;', '}'], output: ["Hello, creator!"] },
};
type Language = keyof typeof snippets;

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [selected, setSelected] = useState<string | null>(null);
  const [language, setLanguage] = useState<Language>("scratch");
  const [running, setRunning] = useState(false);
  const [lines, setLines] = useState<string[]>([]);
  const [paused, setPaused] = useState(false);
  const [burst, setBurst] = useState(0);
  const [copied, setCopied] = useState(false);
  const [copyHelp, setCopyHelp] = useState(false);
  const [reducedMotion, setReducedMotion] = useState(false);
  const course = courses.find((item) => item.id === selected);

  useEffect(() => {
    const media = window.matchMedia("(prefers-reduced-motion: reduce)");
    const update = () => { setReducedMotion(media.matches); setPaused(media.matches); };
    update(); media.addEventListener("change", update);
    return () => media.removeEventListener("change", update);
  }, []);
  useEffect(() => {
    if (!running) return;
    const result = snippets[language].output;
    let index = 0;
    const timer = window.setInterval(() => {
      index += 1; setLines(result.slice(0, index));
      if (index >= result.length) { clearInterval(timer); setRunning(false); }
    }, reducedMotion ? 40 : 440);
    return () => window.clearInterval(timer);
  }, [running, language, reducedMotion]);
  async function copyMessage() {
    const text = `Hi KiddyCody! I’m interested in ${course?.title || "your coding classes"}. Could you tell me about the next group, schedule, and price?`;
    try { await navigator.clipboard.writeText(text); setCopied(true); setCopyHelp(false); }
    catch { setCopyHelp(true); }
  }
  return (
    <div className={paused ? "site motion-paused" : "site"}>
      <a className="skip-link" href="#main">Skip to content</a>
      <header className="site-header">
        <a href="#" className="brand" aria-label="KiddyCody home"><img src="/kiddycody-mark.svg" width="48" height="43" alt="" /><span>Kiddy<span>Cody</span><small>BIG IDEAS START SMALL</small></span></a>
        <nav id="main-navigation" className={`main-nav ${menu ? "nav-open" : ""}`} aria-label="Main navigation"><a onClick={() => setMenu(false)} href="#our-way">Our approach</a><a onClick={() => setMenu(false)} href="#courses">Our courses</a><a onClick={() => setMenu(false)} href="#questions">For parents</a></nav>
        <a className="button header-cta" href="#courses">Let’s get coding <ArrowUpRight size={17} /></a>
        <button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label={menu ? "Close navigation" : "Open navigation"} aria-expanded={menu} aria-controls="main-navigation">{menu ? <X /> : <Menu />}</button>
      </header>
      <main id="main">
        <section className="hero section-container">
          <div className="hero-copy"><div className="eyebrow hero-eyebrow"><span className="eyebrow-icon"><Sparkles size={16} /></span> A BIG HELLO TO LITTLE CREATORS</div><h1>Big ideas<br />start with a<br /><span className="highlight">little code<span className="period">.</span></span></h1><p>A curious mind is a wonderful thing.<br className="desktop-break" /> Let’s give it the tools to create.</p><div className="hero-actions"><a className="button button-coral" href="#courses">Find your coding adventure <ArrowUpRight size={19} /></a><a className="text-link" href="#playground"><Play size={15} fill="currentColor" /> Try a little code</a></div><div className="hero-note"><span className="note-spark">✳</span><span>For curious kids & young minds, <strong>ages 7–20.</strong></span></div></div>
          <div className="hero-visual"><div className="world-orbit orbit-one" aria-hidden="true" /><div className="world-orbit orbit-two" aria-hidden="true" /><div className="world-label"><span className="little-square" /> A WORLD YOU CAN BUILD</div><CodingWorld paused={paused} burst={burst} reducedMotion={reducedMotion} /><div className="floating-code code-flag" aria-hidden="true"><Flag size={17} fill="#1ABC9C" color="#1ABC9C" /><span>when curiosity starts</span></div><div className="floating-code code-hello" aria-hidden="true"><span className="code-angle">&lt;/&gt;</span><span>hello, possibilities!</span><span className="cursor">▌</span></div><div className="float-sticker" aria-hidden="true">Made of<br /><strong>possibilities.</strong><Sparkles size={20}/></div><div className="world-controls"><span><MousePointer2 size={14} /> Move around. Make it yours.</span><button onClick={() => setBurst((value) => value + 1)} aria-label="Remix the 3D building blocks" title="Remix the blocks"><RotateCcw size={16}/><span>Remix</span></button><button aria-label={paused ? "Play animations" : "Pause animations"} onClick={() => setPaused(!paused)} title={paused ? "Play animations" : "Pause animations"}>{paused ? <Play size={15}/> : <Pause size={15}/>}</button></div></div>
        </section>
        <div className="learning-strip"><div className="section-container strip-inner"><span><Monitor /> Live online learning</span><span><Users /> Groups by age</span><span><Puzzle /> Real hands-on projects</span><span><Heart /> Room to be yourself</span></div></div>
        <section id="our-way" className="our-way section-container"><div className="way-heading"><span className="eyebrow">THE KIDDYCODY WAY</span><h2>Less watching.<br /><span className="serif-word">More making.</span></h2></div><div className="way-content"><p>Games. Stories. That “what if?” they can’t stop thinking about. At KiddyCody, we turn curiosity into something they can create—and be proud of.</p><div className="way-points"><div><span className="point-icon yellow"><Lightbulb /></span><h3>Think it.</h3><p>Start with an idea.<br />Ask all the questions.</p></div><div><span className="point-icon blue"><Code2 /></span><h3>Build it.</h3><p>Try, test, and learn.<br />Make it your own.</p></div><div><span className="point-icon coral"><Sparkles /></span><h3>Own it.</h3><p>See what you made.<br />Imagine what’s next.</p></div></div></div></section>
        <section id="courses" className="courses-section"><div className="section-container"><div className="section-heading"><div><span className="eyebrow">SMALL STARTS. EXCITING NEXT STEPS.</span><h2>A path for every<br /><span className="serif-word">curious mind.</span></h2></div><p>From colorful blocks to real lines of code.<br />Find a starting point that feels right.</p></div><div className="course-grid">{courses.map((item) => <article className={`course-card ${item.className}`} key={item.id}><div className="course-card-top"><span className="course-number">{item.number} / LEARNING PATH</span><span className="age-pill">AGES {item.age}</span></div><div className="course-visual" aria-hidden="true">{item.id === "scratch" ? <div className="mini-blocks"><span><Flag size={14} fill="currentColor"/> when adventure begins</span><span>imagine something new</span><span>make it happen <Sparkles size={13}/></span></div> : item.id === "python" ? <div className="python-code"><span>&gt;&gt;&gt; <em>print</em>(<i>"I made this!"</i>)</span><strong>I made this!<span className="code-caret"/></strong></div> : <div className="c-symbol">&#123;<span>C</span>&#125;<small>possibilities, compiled.</small></div>}</div><div className="course-info"><h3>{item.title}</h3><p className="course-subtitle">{item.subtitle}</p><p className="course-description">{item.description}</p><div className="skill-tags">{item.skills.map((skill) => <span key={skill}>{skill}</span>)}</div><button onClick={() => {setSelected(item.id);setCopied(false);setCopyHelp(false);}} className="course-link">Explore {item.title} <ArrowUpRight size={20}/></button></div></article>)}</div><p className="course-footnote"><Users size={17}/> At age 14? Choose a starting point based on experience. We’ll help you find the right fit.</p></div></section>
        <section id="playground" className="playground-section section-container"><div className="playground-copy"><span className="eyebrow"><span className="tiny-plus">+</span> A LITTLE TASTE OF CODING</span><h2>That first<br /><span className="serif-word">“I made it!”</span><br />feeling.</h2><p>Every creator starts somewhere.<br />Pick a language and see a tiny idea come to life.</p><span className="playground-aside"><ArrowRight size={18}/> Go on. Press play.</span></div><div className="playground-window"><div className="window-title"><div className="window-dots" aria-hidden="true"><i/><i/><i/></div><span>the little coding playground</span><Code2 size={17}/></div><Tabs value={language} onValueChange={(value) => {setLanguage(value as Language);setRunning(false);setLines([]);}}><TabsList className="language-tabs" aria-label="Choose a coding example"><TabsTrigger value="scratch">Scratch</TabsTrigger><TabsTrigger value="python">Python</TabsTrigger><TabsTrigger value="c">C</TabsTrigger></TabsList>{(Object.keys(snippets) as Language[]).map((lang) => <TabsContent value={lang} key={lang} className="code-tab"><div className={`code-editor ${lang === "scratch" ? "block-editor" : ""}`} aria-label={`${lang} example code`}>{snippets[lang].code.map((line,index) => lang === "scratch" ? <div key={index} className={`sample-block sample-block-${index}`}>{index === 0 && <Flag size={14} fill="currentColor"/>}{line}</div> : <div className="editor-line" key={index}><span className="line-number">{index+1}</span><code>{line || " "}</code></div>)}</div></TabsContent>)}</Tabs><div className="run-row"><span><span className="example-square"/> A tiny example. A real beginning.</span><button className="run-button" disabled={running} onClick={() => {setLines([]);setRunning(true);}}><Play size={14} fill="currentColor"/>{running ? "Playing…" : "Play example"}</button></div><div className="output-pane"><span className="output-label">OUTPUT PREVIEW</span><div className="output-lines" role="status" aria-live="polite" aria-atomic="true">{lines.length ? lines.map((line,index) => <p key={index}><span>›</span> {line}</p>) : <p className="output-empty">Your first hello is one click away.<span className="terminal-cursor"/></p>}</div></div></div></section>
        <section className="parent-note"><div className="section-container parent-note-inner"><div className="parent-note-mark" aria-hidden="true">✳</div><p>Built for their imagination.<br /><strong>Designed around real life.</strong></p><div><p>Live online lessons. Guidance as they learn.<br />A space to ask questions, make mistakes, and try again.</p><a className="text-link" href="#questions">A few things parents ask <ArrowDown size={16}/></a></div></div></section>
        <section id="questions" className="faq-section section-container"><div className="faq-heading"><span className="eyebrow">GOOD QUESTIONS. SIMPLE ANSWERS.</span><h2>Curious?<br /><span className="serif-word">So are we.</span></h2><p>Here’s a little more about learning with KiddyCody.</p></div><Accordion type="single" collapsible className="faq-list"><AccordionItem value="start"><AccordionTrigger>Does my child need any coding experience?</AccordionTrigger><AccordionContent>No experience is needed to start with Scratch. For Python and C, tell us the student’s age and experience so we can recommend a suitable starting point.</AccordionContent></AccordionItem><AccordionItem value="online"><AccordionTrigger>How do the classes work?</AccordionTrigger><AccordionContent>Classes are taught live online, with students grouped by age. They learn by working on projects and asking questions along the way. Message us for the schedule and format of the next group.</AccordionContent></AccordionItem><AccordionItem value="device"><AccordionTrigger>What will we need for a class?</AccordionTrigger><AccordionContent>A laptop or desktop computer, a stable internet connection, and a curious mind. We’ll explain which software to set up before the course starts.</AccordionContent></AccordionItem><AccordionItem value="choose"><AccordionTrigger>Which course should we choose?</AccordionTrigger><AccordionContent>Scratch is for ages 7–14 and introduces coding through visual blocks. Python and C are for ages 14–20. If a student is 14 or you’re unsure where to begin, we can help you choose based on their experience and interests.</AccordionContent></AccordionItem><AccordionItem value="join"><AccordionTrigger>How do we join, and how much does it cost?</AccordionTrigger><AccordionContent>Message KiddyCody on WhatsApp with the student’s age and preferred course. We’ll share current prices, upcoming groups, and registration details. <a href={whatsapp()} target="_blank" rel="noopener noreferrer">Chat with KiddyCody on WhatsApp <ArrowUpRight size={14}/></a></AccordionContent></AccordionItem></Accordion></section>
        <section id="contact" className="contact-section section-container"><div className="contact-panel"><span className="contact-spark" aria-hidden="true">✳</span><span className="eyebrow">THE NEXT BIG IDEA COULD BE THEIRS.</span><h2>Let’s make room<br />for <span className="serif-word">possibility.</span></h2><p>A first game. A clever little program. A whole new confidence.<br />It all starts with a hello.</p><a className="button button-dark" href={whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={20}/> Say hello on WhatsApp <ArrowUpRight size={18}/></a><span className="contact-handle">+961 81 954 659 <span aria-hidden="true"> · </span><a href={instagram} target="_blank" rel="noopener noreferrer">Find us on Instagram <ArrowUpRight size={13}/></a></span><div className="contact-code" aria-hidden="true">&lt;imagine&gt;<br /><span>&nbsp; anything.</span><br />&lt;/imagine&gt;</div></div></section>
      </main>
      <footer className="site-footer section-container"><a href="#" className="brand"><img src="/kiddycody-mark.svg" alt="" width="42" height="38"/><span>Kiddy<span>Cody</span></span></a><span>Little steps. Lifelong possibilities.</span><div><a href={instagram} target="_blank" rel="noopener noreferrer" aria-label="KiddyCody on Instagram"><Instagram size={20}/></a><span>© {new Date().getFullYear()} KiddyCody</span></div></footer>
      <Dialog open={!!selected} onOpenChange={(open) => {if (!open) setSelected(null);}}><DialogContent className="course-dialog">{course && <><span className={`dialog-course-tag ${course.className}`}>AGES {course.age} · LIVE ONLINE</span><DialogTitle>{course.title}</DialogTitle><DialogDescription>{course.detail}</DialogDescription><h4>What we’ll explore</h4><ul className="dialog-outcomes">{course.outcomes.map((outcome) => <li key={outcome}><Check size={17}/>{outcome}</li>)}</ul><div className="project-note"><Lightbulb size={20}/><p><strong>Ideas to bring to life</strong>{course.examples}</p></div><p className="registration-note">Ask us about the next group, class schedule, and current price.</p><a className="button button-dark dialog-cta" href={whatsapp(course.title)} target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/> Ask about this course <ArrowUpRight size={18}/></a><button className="copy-message" onClick={copyMessage}>{copied ? <Check size={15}/> : <Copy size={15}/>} {copied ? "Message copied — paste it into your chat" : "Copy a ready-to-send message"}</button>{copyHelp && <textarea aria-label="Registration message to copy" readOnly defaultValue={`Hi KiddyCody! I’m interested in ${course.title}. Could you tell me about the next group, schedule, and price?`} onFocus={(event) => event.target.select()}/>}</>}</DialogContent></Dialog>
    </div>
  );
}
